version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pgc-app:latest
    container_name: pgc-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Frontend environment variables (replace with your values)
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    env_file:
      - .env.docker  # Create this file with your secrets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - pgc-network

networks:
  pgc-network:
    driver: bridge
