version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pgc-app:latest
    container_name: pgc-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env.docker  # All secrets and config go here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - pgc-network

networks:
  pgc-network:
    driver: bridge
